<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="family" nsURI="ecore://nasdanika.org/models/family" nsPrefix="org.nasdanika.models.family">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="A model of a family consisting of persons "/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Family" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Person" containment="true" eKeys="../../org.nasdanika.ncore/model/ncore.ecore#//StringIdentity/id"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true" eSuperTypes="../../org.nasdanika.models.party/model/party.ecore#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfBirth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Person" eOpposite="#//Person/parents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parents" upperBound="2"
        eType="#//Person" eOpposite="#//Person/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mother" eType="#//Woman"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="father" eType="#//Man"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Man" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Woman" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Polity" eSuperTypes="../../org.nasdanika.ncore/model/ncore.ecore#//DocumentedNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constituents" upperBound="-1"
        eType="#//Polity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="residents" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
